### PR TITLE
Loops

### LINKED ISSUE #14: Slides for loops
Let's rewrite the loops slides

### PR DESCRIPTION
**Pull request by lxxxvi**
closes #14

### CODE REVIEW

**Comment by nerdinand** [comment]
I wonder whether we can somehow visually make it clearer how Ruby executes the code. Maybe the way it would look in a debugger, pointing to the next line that will be executed, then taking a step. This would allow to explain how Ruby execution is jumping around in the file, which may not be clear otherwise.

**Comment by nerdinand** [comment]
@hharen Yes, since we have so few slides in this one, it might make sense to add more loop constructs. The problem is of course we should then also have exercises for them... ;)
In the old slides we have `each` in this slideset as well. We should probably at least add that.

**Comment by lxxxvi** [comment]
> I wonder whether we can somehow visually make it clearer how Ruby executes the code. Maybe the way it would look in a debugger, pointing to the next line that will be executed, then taking a step. This would allow to explain how Ruby execution is jumping around in the file, which may not be clear otherwise.

Letme try that.

**Comment by lxxxvi** [comment]
> Seems perfect :)
> 
> Maybe we'd want to add also others to this slide set? Like until, while, each, ...? What do you guys think?

@hharen 

My opinion: 

We should not spend much time on `while`-, `until`- and `for`-loops. I'm OK if we demonstrate them somewhere (like an appendix slide set?) but we should not have exercises for them.
Reason: They're confusing when it comes to the question "When should I use which loop-style?", my answer would probably be: don't use them at all 😁 

Instead I would focus on Enumerables like `.each`, `.map`, `.find`, `.find_all` etc, but this should be covered in separate slides.

other opinions? @nerdinand

**Comment by nerdinand** [comment]
@lxxxvi Yeah, I also like the idea to only really teach `loop` and `each`. Maybe let them explore `while` and `until` in some exercise. À la: 

1. Do x with a `loop`
2. There is another loop construct that is perfect for this case, it's called `while`. Rewrite your code using that (google to find out how to use it).

That way, they don't get it shown to them in the slides, but they can figure out how it works on their own. I expect that to be less confusing than just seeing some slides, where everything seems obvious but isn't...

**Comment by hharen** [comment]
So should we merge it and then think about how to visualize the loop?

**Comment by nerdinand** [comment]
Yeah, i think we should merge this finally @lxxxvi and add it to the website too. We can improve it later...

**Pull request merged**
